### ISSUE TITLE
library not working with junit5 (org.junit.jupiter v. 5.1.0)

### ISSUE THREAD

**Issue by bgalamb** [marcelstoer/junit-references#1]
The library does not work anymore with the latest Junit (Junit 5). 
The whole concept has been redesigned from Junit4 to Junit5. 
Now you should use extensions -extension classes- (see https://www.baeldung.com/junit-5-extensions ) Instead of RunListeners (https://www.swtestacademy.com/junit-listeners/).  

It would be highly appreciated if you enhanced the library to make it compatible again.

Balazs

**Comment by marcelstoer** [comment]
Sorry, see update in README.
